name: Test Build Workflow
run-name: Test Build Workflow ${{ github.actor }} 🚀

on:
  push:
    tags:
      - build_*

env:
  GITHUB_REF_NAME: ${{ github.ref_name }}

jobs:
  Build-Static-Libs:
    runs-on: ubuntu-latest
    steps:
      - name: Set Build Version
        run: |
          echo "build_version=${GITHUB_REF_NAME##build_}" >> "$GITHUB_ENV"

      - name: Checkout Version
        uses: actions/checkout@v4
        with:
          ref: ${{ env.build_version }}

      - name: Show Me
        run: |
          git tag --list